repos:
    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        - id: black
          language_version: python3.8
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.782
        hooks:
        - id: mypy
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.3  # pick a git hash / tag to point to
        hooks:
        - id: flake8
    -   repo: https://github.com/pycqa/isort
        rev: 5.5.1
        hooks:
        - id: isort